[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true


[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.1.0",
    "pytest==7.0.1",
    "pytest-django>=4.5.2",
    "mypy>=0.931",
    "django-debug-toolbar>=3.2.4",
    "coverage==6.3.2",
]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE='app.settings.test'
testpaths = [
    "src/",
]
addopts = "--rootdir ./src --disable-warnings"
filterwarnings = 'ignore:function ham\(\) RemovedInDjango40Warning'  # Not Include Django 4.0 Deprecation Warnings

[project]
name = "levoagora_backend"
version = "0.0.1"
description = ""
authors = [
    {name = "Leandro de Souza", email = "leandrodesouzadev@gmail.com"},
]
dependencies = [
    "amqp==5.0.7",
    "asgiref==3.4.1",
    "backports.zoneinfo==0.2.1",
    "billiard==3.6.4.0",
    "certifi==2021.10.8",
    "charset-normalizer==2.0.9",
    "celery==5.2.2",
    "click-didyoumean==0.3.0",
    "click-plugins==1.1.1",
    "click-repl==0.2.0",
    "coreapi==2.3.3",
    "coreschema==0.0.4",
    "coreapi==2.3.3",
    "coreschema==0.0.4",
    "django==3.2.10",
    "django-cors-headers==3.10.1",
    "django-environ==0.8.1",
    "django-material-admin==1.8.5",
    "djangorestframework==3.13.0",
    "djangorestframework-simplejwt==5.0.0",
    "drf-yasg==1.20.0",
    "idna==3.3",
    "inflection==0.5.1",
    "itypes==1.2.0",
    "jinja2==3.0.3",
    "kombu==5.2.2",
    "markupsafe==2.0.1",
    "prompt-toolkit==3.0.24",
    "psycopg2-binary==2.9.2",
    "pyjwt==2.3.0",
    "pytz==2021.3",
    "requests==2.26.0",
    "ruamel.yaml==0.17.17",
    "ruamel.yaml.clib==0.2.6",
    "sqlparse==0.4.2",
    "uritemplate==4.1.1",
    "urllib3==1.26.7",
    "vine==5.0.0",
    "wcwidth==0.2.5",
    "whitenoise==5.3.0",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
